POST  http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF3cyIsImlkIjoiNjNjZTkwNDFhNmFkZDUwZWZkZGEyNTZkIiwiaWF0IjoxNjc0NTA0Njc3LCJleHAiOjE2NzQ1MDgyNzd9.ipLHnGpU_n-vVQ6nJ1JB76KBx8a8C01hVC6WiO0OmdM

{
    "title": "blog with user from Authorization fix Bearer",
    "author": "unknown",
    "url": "www.unkown.com",
    "likes": 1
}